[package]
name = "SystemProgrammingProject1"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
log = "0.4"
simplelog = "0.11"

[[bin]]
name = "Version1"
path = "src/Version1.rs"

[[bin]]
name = "Version2"
path = "src/Version2.rs"
