[package]
name = "SystemProgrammingProject1"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"

[[bin]]
name = "Version1"
path = "src/main.rs"

[[bin]]
name = "Version2"
path = "src/version2.rs"
